name: Hexo Deploy

# 只监听 dev 分支的改动
on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: dev # 根据实际触发的分支修改，如果是别的分支就替换dev

      # 设置Node.js环境，这里以16.x为例，你可以按需修改版本
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: |
          npm install -g gulp
          npm install -g hexo-cli
          npm install

      # 执行hexo生成命令和 gulp 压缩
      - name: Generate Hexo site
        run: |
          hexo clean & hexo g
          gulp
      
      - name: Print directory tree
        run: |
          find . -maxdepth 1 -type d -not -name '.' -not -name '..' -exec basename {} \;

      # 进入 public 目录
      - name: Cd public dir
        run: |
          cd ./public

      - name: Print current working directory
        run: |
          pwd

      # 获取当前时间
      - name: Get current time
        id: get_time
        run: echo "::set-output name=time::$(date +'%Y-%m-%d %H:%M:%S')"

      # 构建并写入README.md内容
      - name: Update README.md
        run: |
          cat << EOF >> README.md
          # Merrier说
          使用Hexo进行搭建，利用GitHub Action实现持续集成
          ## 自动部署集成日志
          部署状态 | 集成结果 | 参考值
          ---|---|---
          完成时间 | ${{ steps.get_time.outputs.time }} | yyyy-mm-dd hh:mm:ss
          部署环境 | ${{ runner.os }} + ${{ matrix.node-version }} | window | linux + 对应版本号
          部署类型 | ${{ github.event_name }} | push | pull_request | 其他类型等
          仓库地址 | ${{ github.repository }} | owner_name/repo_name
          提交分支 | ${{ github.sha }} | hash值
          提交信息 | ${{ github.event.commits[0].message }} |
          Job ID   | ${{ github.run_id }} |
          Job NUM  | ${{ github.run_number }} |
          EOF
      # 初始化Git仓库
      - name: Initialize Git
        run: |
          git init

      # 配置Git用户信息
      - name: Configure Git
        run: |
          git config user.name "merrier"
          git config user.email "953075999@qq.com"

      # 添加文件到暂存区
      - name: Add files
        run: |
          git add .

      # 提交更改
      - name: Commit changes
        run: |
          git commit -m "Update Blog By GitHub Action With Build ${{ github.run_number }}"

      # 创建 master 分支
      - name: Checkout new branch
        run: |
          git checkout -b master

      - name: Test Secret GH_TOKEN Variable
        run: |
          echo "Secret variable exists and can be accessed"
          if [ -n "${{ secrets.GH_TOKEN }}" ]; then
            echo "GH_TOKEN variable is not empty"
          else
            echo "GH_TOKEN variable is empty or not set correctly"
          fi

      - name: Test Secret GH_TOKEN Variable
        run: |
          echo "Secret variable exists and can be accessed"
          if [ -n "${{ secrets.GH_REF }}" ]; then
            echo "GH_REF variable is not empty"
          else
            echo "GH_REF variable is empty or not set correctly"
          fi

      - name: Print current branch
        run: |
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          echo "The current branch is: $current_branch"

      - name: Add remote repository
        run: |
          git remote add target_repo https://${{ secrets.GH_TOKEN }}@${{ secrets.GH_REF }}

      # 推送更改到master分支
      - name: Push to master
        run: |
          git push --force --quiet "https://${{ secrets.GH_TOKEN }}@${{ secrets.GH_REF }}" master:master

      # 创建标签
      - name: Create Tag
        run: |
          git tag v1.1.${{ github.run_number }} -a -m "Auto Tagged By GitHub Action With Build ${{ github.run_number }}"

      # 推送标签
      - name: Push Tags
        run: |
          git push --quiet "https://${{ secrets.GH_TOKEN }}@${{ secrets.GH_REF }}" master:master --tags
