name: Hexo Deploy

# 只监听 dev 分支的改动
on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3
      # 设置Node.js环境，这里以16.x为例，你可以按需修改版本
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"
      - name: Install Dependencies
        run: |
          npm install -g gulp
          npm install -g hexo-cli
          npm install
      # 执行hexo生成命令
      - name: Generate Hexo site
        run: hexo clean & hexo g
      # 获取当前日期和时间
      - name: Get current date and time
        id: get_date
        run: echo "::set - output name=date::$(date +'%Y-%m-%d %H:%M:%S')"

      # 修改README.md内容
      - name: Modify README.md
        run: |
          echo "## Deployment Date and Time: ${{steps.get_date.outputs.date}}" >> README.md
          sed -i '1i\\# README - Updated for Hexo Deployment' README.md
      # 将生成的内容添加到暂存区
      - name: Add generated files
        run: git add .
      # 提交更改，这里的提交信息可以按需修改
      - name: Commit changes
        run: git commit -m "feat:\ Auto deploy generated Hexo site"
      # 将更改推送到master分支
      - name: Push to master
        run: |
          git push origin master
